version: '3'
services:
    echarts:
        environment:
            - NODE_ENV=development
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src/:/usr/src/app
        container_name: echarts
        expose:
            - 8080
        ports:
            - 8080:8080
        restart: on-failure
        command: nodemon server.js
